# Generated by Django 5.2.6 on 2025-09-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_attempt_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('INSTRUCTOR', 'Instructor'), ('STUDENT', 'Student'), ('DEPARTMENT_HEAD', 'Department Head'), ('HR', 'HR')], default='STUDENT', max_length=20),
        ),
    ]
